vim.api.nvim_set_keymap('', '<Space>', '<Nop>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', 'jj', '<esc>', { noremap = true })
vim.api.nvim_set_keymap('n', 'vv', '<c-w>v', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>ee', ':tabe $MYVIMRC<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>es', ':source $MYVIMRC<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '[q', ':cp<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', ']q', ':cn<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-l>', '<c-w>l', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-k>', '<c-w>k', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-j>', '<c-w>j', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-h>', '<c-w>h', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>gg', ':Git<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>gb', ':Git blame<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<c-p>', ':Telescope find_files<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>pg', ':Telescope live_grep<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>pb', ':Telescope buffers<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>pt', ':Telescope tags<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>pp', ':Telescope current_buffer_tags<cr>', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>tt', ':tabe term://$SHELL<CR>a', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>tv', ':vs term://$SHELL<CR>a', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>ts', ':sp term://$SHELL<CR>a', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>tb', ':Tagbar<CR>', { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>xx", "<cmd>TroubleToggle<cr>", { silent = true, noremap = true  })
vim.api.nvim_set_keymap("n", "<leader>xw", "<cmd>TroubleToggle workspace_diagnostics<cr>", { silent = true, noremap = true })
vim.api.nvim_set_keymap("n", "<leader>xd", "<cmd>TroubleToggle document_diagnostics<cr>", { silent = true, noremap = true })
vim.api.nvim_set_keymap("n", "<leader>xl", "<cmd>TroubleToggle loclist<cr>", { silent = true, noremap = true })
vim.api.nvim_set_keymap("n", "<leader>xq", "<cmd>TroubleToggle quickfix<cr>", { silent = true, noremap = true })
vim.api.nvim_set_keymap("n", "gR", "<cmd>TroubleToggle lsp_references<cr>", { silent = true, noremap = true })
-- vim.api.nvim_set_keymap('n', '<leader>tt', ':TestLast<cr>', { noremap = true })
-- vim.api.nvim_set_keymap('n', '<leader>tf', ':TestFile<cr>', { noremap = true })
-- vim.api.nvim_set_keymap('n', '<leader>tn', ':TestNearest<cr>', { noremap = true })
-- vim.api.nvim_set_keymap('n', '<leader>ta', ':TestSuite<cr>', { noremap = true })
-- vim.api.nvim_set_keymap('n', '<leader>tq', ':cclose<cr>', { noremap = true })

